# Generated by Django 2.2.12 on 2020-06-09 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_education'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='location',
            field=models.CharField(default='london', max_length=64),
            preserve_default=False,
        ),
    ]
