# Generated by Django 2.2.12 on 2020-06-09 16:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_education_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='end_year',
            field=models.PositiveIntegerField(default=2020, validators=[django.core.validators.MinValueValidator(1984), django.core.validators.MaxValueValidator(3000)]),
        ),
        migrations.AlterField(
            model_name='education',
            name='start_year',
            field=models.PositiveIntegerField(default=2020, validators=[django.core.validators.MinValueValidator(1984), django.core.validators.MaxValueValidator(3000)]),
        ),
    ]
