# Generated by Django 2.2.12 on 2020-06-18 13:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_techskills'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('start_date', models.DateTimeField(default=datetime.datetime(2020, 6, 18, 13, 22, 12, 131405, tzinfo=utc))),
                ('end_date', models.DateTimeField(default=datetime.datetime(2020, 6, 18, 13, 22, 12, 131405, tzinfo=utc))),
            ],
        ),
    ]
