# Generated by Django 2.2.12 on 2020-06-18 16:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20200618_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='workexperience',
            name='location',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
